# Generated by Django 4.2.9 on 2025-03-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DnDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['status']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['campaign']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['campaign']},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['campaign']},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['campaign']},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['campaign']},
        ),
    ]
